// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Homework.DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Homework.DataAccess.Models
{
    public partial interface IMercuryfireHomeworkContextProcedures
    {
        Task<int> NEWSIDAsync(string tableName, OutputParameter<string> returnSID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_AddLogAsync(byte? _InBox_ReadID, string _InBox_SPNAME, Guid? _InBox_GroupID, string _InBox_ExProgram, string _InBox_ActionJSON, OutputParameter<string> _OutBox_ReturnValues, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
