// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Homework.DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Homework.DataAccess.Models
{
    public partial class MercuryfireHomeworkContext
    {
        private IMercuryfireHomeworkContextProcedures _procedures;

        public virtual IMercuryfireHomeworkContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MercuryfireHomeworkContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMercuryfireHomeworkContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class MercuryfireHomeworkContextProcedures : IMercuryfireHomeworkContextProcedures
    {
        private readonly MercuryfireHomeworkContext _context;

        public MercuryfireHomeworkContextProcedures(MercuryfireHomeworkContext context)
        {
            _context = context;
        }

        public virtual async Task<int> NEWSIDAsync(string tableName, OutputParameter<string> returnSID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterReturnSID = new SqlParameter
            {
                ParameterName = "ReturnSID",
                Size = 40,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = returnSID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "TableName",
                    Size = 256,
                    Value = tableName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterReturnSID,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[NEWSID] @TableName = @TableName, @ReturnSID = @ReturnSID OUTPUT", sqlParameters, cancellationToken);

            returnSID?.SetValue(parameterReturnSID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> usp_AddLogAsync(byte? _InBox_ReadID, string _InBox_SPNAME, Guid? _InBox_GroupID, string _InBox_ExProgram, string _InBox_ActionJSON, OutputParameter<string> _OutBox_ReturnValues, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameter_OutBox_ReturnValues = new SqlParameter
            {
                ParameterName = "_OutBox_ReturnValues",
                Size = -1,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = _OutBox_ReturnValues?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "_InBox_ReadID",
                    Value = _InBox_ReadID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "_InBox_SPNAME",
                    Size = 240,
                    Value = _InBox_SPNAME ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "_InBox_GroupID",
                    Value = _InBox_GroupID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "_InBox_ExProgram",
                    Size = 80,
                    Value = _InBox_ExProgram ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "_InBox_ActionJSON",
                    Size = -1,
                    Value = _InBox_ActionJSON ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameter_OutBox_ReturnValues,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[usp_AddLog] @_InBox_ReadID = @_InBox_ReadID, @_InBox_SPNAME = @_InBox_SPNAME, @_InBox_GroupID = @_InBox_GroupID, @_InBox_ExProgram = @_InBox_ExProgram, @_InBox_ActionJSON = @_InBox_ActionJSON, @_OutBox_ReturnValues = @_OutBox_ReturnValues OUTPUT", sqlParameters, cancellationToken);

            _OutBox_ReturnValues?.SetValue(parameter_OutBox_ReturnValues.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
