// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Homework.DataAccess.Models;

public partial class MyOfficeExcuteionLog
{
    public long DeLogAutoId { get; set; }

    public string DeLogStoredPrograms { get; set; }

    public Guid DeLogGroupId { get; set; }

    public bool DeLogIsCustomDebug { get; set; }

    public string DeLogExecutionProgram { get; set; }

    public string DeLogExecutionInfo { get; set; }

    public bool? DeLogVerifyNeeded { get; set; }

    public DateTime DeLogExDateTime { get; set; }
}